// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz04H9CC0vF7KciRAf9tH2NoUQnZQX0hw',
    appId: '1:1092637093156:web:08a620cea73e399fe8d7b1',
    messagingSenderId: '1092637093156',
    projectId: 'chatapp-da28a',
    authDomain: 'chatapp-da28a.firebaseapp.com',
    storageBucket: 'chatapp-da28a.appspot.com',
    measurementId: 'G-F9713NW84G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDOJxfs48m16mBke4XW8CqKcy9JPTXQDQ',
    appId: '1:1092637093156:android:039110dbd9e104f4e8d7b1',
    messagingSenderId: '1092637093156',
    projectId: 'chatapp-da28a',
    storageBucket: 'chatapp-da28a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-_9Ljzo_R281rfqcTk9VESJdMH0JtsIk',
    appId: '1:1092637093156:ios:b877c032de41d0d1e8d7b1',
    messagingSenderId: '1092637093156',
    projectId: 'chatapp-da28a',
    storageBucket: 'chatapp-da28a.appspot.com',
    iosClientId:
        '1092637093156-rl2kjajuu3fduq2u0b1b5p2vrnf6j91r.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-_9Ljzo_R281rfqcTk9VESJdMH0JtsIk',
    appId: '1:1092637093156:ios:c110737f55ed7b6de8d7b1',
    messagingSenderId: '1092637093156',
    projectId: 'chatapp-da28a',
    storageBucket: 'chatapp-da28a.appspot.com',
    iosClientId:
        '1092637093156-480vmbmev1nvp5h9evkp5hfiuf5vdvjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
